[package]
name = "otp-conn"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
serial = "0.4.0"
otp = { path = "../otp"}
